import assert from 'node:assert/strict';
import {webcrypto} from 'node:crypto';
const data=new Map();globalThis.window={crypto:webcrypto};globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v),removeItem:k=>data.delete(k)};
const {writeObject,readObject}=await import('../js/core/storage.js');
const a=await import('../js/services/admin.service.js');const auth=await import('../js/core/auth.js');
const admin={id:'admin',name:'Admin',email:'admin@test.ci',role:'OIC_ADMIN'};
writeObject('dut_users',[admin]);writeObject('dut_current_user',admin);writeObject('dut_partners',[{id:'p1',name:'Partenaire',antennaId:'a1'}]);
const result=await a.saveUser(null,{name:'Utilisateur',email:'u@test.ci',role:'PARTNER_EDITOR',scope:'p1'});assert.ok(result.code);assert.equal(result.user.partnerId,'p1');assert.equal(a.directory().users[1].credential,undefined);
await assert.rejects(a.saveUser(null,{name:'Doublon',email:'U@test.ci',role:'CONTROLLER'}),/déjà/);
await assert.rejects(a.saveUser(null,{name:'Sans périmètre',email:'s@test.ci',role:'PARTNER_EDITOR'}),/rattachement/);
await assert.rejects(a.saveUser(admin.id,{...admin,role:'CONTROLLER'}),/propre rôle/);assert.throws(()=>a.setActive(admin.id,false),/propre compte/);
await auth.login('u@test.ci',result.code);assert.equal(auth.getCurrentUser().id,result.user.id);assert.throws(()=>a.directory(),/réservé/);const session=readObject('dut_current_user');
writeObject('dut_current_user',admin);a.setActive(result.user.id,false);writeObject('dut_current_user',session);assert.equal(auth.getCurrentUser(),null);await assert.rejects(auth.login('u@test.ci',result.code),/invalides/);
writeObject('dut_current_user',admin);a.setActive(result.user.id,true);const code=await a.resetAccess(result.user.id);await assert.rejects(auth.login('u@test.ci',result.code),/invalides/);await assert.rejects(auth.login('u@test.ci','demo123'),/invalides/);await auth.login('u@test.ci',code);
writeObject('dut_current_user',admin);await a.saveUser(result.user.id,{name:'Utilisateur',email:'u@test.ci',role:'CONTROLLER'});assert.equal(a.directory().users[1].partnerId,undefined);
const saved=a.saveSettings({platformName:'OIC Test',supportEmail:'a@test.ci',overdueDays:4,rangeQuantity:50,rangePrice:1500});assert.equal(a.settings().rangeQuantity,50);assert.throws(()=>a.saveSettings({...saved,overdueDays:0}),/seuil/);assert.equal(a.settings().overdueDays,4);assert.ok(!JSON.stringify(a.history()).includes(code));assert.ok(!JSON.stringify(a.history()).includes(result.code));
await auth.login(admin.email,'demo123');assert.equal(auth.getCurrentUser().role,'OIC_ADMIN');console.log('Administration : comptes, périmètres, rôles, sessions invalidées, réinitialisation et paramètres validés.');
const beforeUsers=readObject('dut_users'),beforeLogs=a.history();const normalSet=localStorage.setItem;
localStorage.setItem=(k,v)=>{if(k==='dut_users')throw new Error('Quota');normalSet(k,v);};
assert.throws(()=>a.setActive(result.user.id,false),/stockage/);localStorage.setItem=normalSet;
assert.deepEqual(readObject('dut_users'),beforeUsers);assert.deepEqual(a.history(),beforeLogs);
