import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { webcrypto } from 'node:crypto';
import fs from 'node:fs';
const require=createRequire(import.meta.url);
const {jsPDF}=require('../js/vendor/jspdf.umd.min.js');
globalThis.window={crypto:webcrypto};
const data=new Map();globalThis.localStorage={getItem:k=>data.get(k)||null,setItem:(k,v)=>data.set(k,v)};
const {seedDemoData}=await import('../js/seed.js');seedDemoData();
const {readCollection,writeObject}=await import('../js/core/storage.js');
const {printPayload,fingerprint,commitPrint,verifyPrint,canonical,printState,nextRank}=await import('../js/services/dut-print.service.js');
const {buildDutPdf}=await import('../js/services/dut-pdf-layout.js');
const {updateDut}=await import('../js/repositories/dut.repository.js');
const user=readCollection('dut_users').find(u=>u.role==='OIC_ADMIN');writeObject('dut_current_user',user);
const dut=readCollection('dut_list').find(d=>d.status==='VALIDE');
dut.qrToken='00000000-0000-4000-8000-000000000001';
Object.assign(dut.general,{driverPiece:'CNI 00219845102'});
Object.assign(dut.expediteur,{adresse:'Plateau, Abidjan',contact:'+225 27 20 21 22 23',registre:'CI-ABJ-2009-B-887',reference:'REF-1003'});
Object.assign(dut.destinataire,{adresse:'Zone industrielle, Bouaké',contact:'+225 31 60 61 62 63',registre:'CI-BKE-2013-B-410',reference:'REF-D-1003'});
dut.marchandises=[{designation:'Sacs de cacao marchand',nature:'Produit agricole',emballage:'Sacs',quantite:420,poidsTonnes:26,volumeM3:48,valeur:31500000,devise:'FCFA'},{designation:'Palettes vides',nature:'Matériel',emballage:'Palettes',quantite:36,poidsTonnes:2.4,volumeM3:9.6,valeur:1800000,devise:'FCFA'}];
Object.assign(dut.facturation.expediteur,{prixTransport:1850000,accessoires:180000,complementaires:70000});
Object.assign(dut.facturation.destinataire,{accessoires:200000,complementaires:150000});
Object.assign(dut.annexes,{emballages:'Sacs de jute 64 kg, palettes consignées',instructions:'Bâchage obligatoire. Déchargement sous contrôle du destinataire aux heures ouvrables.',pieces:[{name:'Bon de livraison'},{name:'Certificat phytosanitaire'}]});
updateDut(dut.id,dut);
const logo='data:image/jpeg;base64,'+fs.readFileSync('assets/images/logo-oic.jpg').toString('base64');
const emblem='data:image/png;base64,'+fs.readFileSync('assets/images/armoiries-ci.png').toString('base64');
fs.mkdirSync('tmp/pdfs',{recursive:true});fs.mkdirSync('output/pdf',{recursive:true});
const qr='data:image/png;base64,'+fs.readFileSync('tests/fixtures/qr-print.png').toString('base64');
const payload=printPayload(dut);const hash=await fingerprint(payload);
assert.equal(hash.length,64);assert.equal(canonical({b:2,a:1}),canonical({a:1,b:2}));
const changed=structuredClone(payload);changed.document.general.immatriculation='MODIFIE';assert.notEqual(hash,await fingerprint(changed));
const sample=buildDutPdf(jsPDF,payload,hash,{logo,emblem,qr});assert.equal(sample.getNumberOfPages(),2);
fs.writeFileSync('output/pdf/dut-revise-exemple.pdf',Buffer.from(sample.output('arraybuffer')));
commitPrint(payload,hash,'');assert.equal(nextRank(dut),2);assert.equal((await verifyPrint(dut,1,hash)).ok,true);assert.equal((await verifyPrint(dut,1,'a'.repeat(64))).ok,false);
const repeated=printPayload(dut);assert.throws(()=>commitPrint(repeated,hash,''),/motif/);
updateDut(dut.id,{status:'SUSPENDU',suspendedAt:new Date().toISOString()});assert.throws(()=>commitPrint(repeated,hash,'test'),/changé/);
for(const status of ['EN_EDITION','TERMINE','REJETE','SUSPENDU','RETIRE']) {
 const item={...dut,status};const p=printPayload(item);const h=await fingerprint(p);const pdf=buildDutPdf(jsPDF,p,h,{logo,emblem,qr});assert.equal(pdf.getNumberOfPages(),2);fs.writeFileSync(`tmp/pdfs/etat-${status}.pdf`,Buffer.from(pdf.output('arraybuffer')));assert.ok(printState(item).warning);
}
const long=structuredClone(dut);long.marchandises=Array.from({length:45},(_,i)=>({...dut.marchandises[0],designation:'Marchandise détaillée '+i}));long.annexes.instructions='Instructions longues à conserver intégralement. '.repeat(120);
const lp=printPayload(long);const lpdf=buildDutPdf(jsPDF,lp,await fingerprint(lp),{logo,emblem,qr});assert.ok(lpdf.getNumberOfPages()>2);fs.writeFileSync('tmp/pdfs/long.pdf',Buffer.from(lpdf.output('arraybuffer')));
console.log('PDF : 2 pages standard ; variantes de statut, débordements, hash sensible aux champs, historique et validation des rangs vérifiés.');
