import assert from 'node:assert/strict';
import { webcrypto } from 'node:crypto';
const data = new Map();
let fail = false;
globalThis.window = { crypto: webcrypto };
globalThis.localStorage = { getItem: k => data.get(k) || null, setItem: (k,v) => { if (fail) throw new Error('QuotaExceeded'); data.set(k,v); }, removeItem: k => data.delete(k) };
globalThis.FileReader = class { readAsDataURL(file) { this.result = `data:${file.type};base64,dGVzdA==`; this.onload(); } };
const { writeObject, readObject } = await import('../js/core/storage.js');
const { blankDut } = await import('../js/services/dut.service.js');
const { addDut, findDutById } = await import('../js/repositories/dut.repository.js');
const w = await import('../js/services/workspace.service.js');
const ops = await import('../js/services/operations.service.js');
const user = { id:'partner',role:'PARTNER_ADMIN',partnerId:'p1',name:'Partenaire test' };
setPersona( user);
const dut = blankDut(user); dut.status='VALIDE'; dut.dutNumber='DUT-CI-2026-000100'; dut.qrToken='secret'; dut.validatedAt='2026-09-21'; dut.general.transporterId='t1'; dut.antennaId='a1';
addDut(dut);
assert.equal(w.dossier(dut.id).stage,'PLANNED');
assert.throws(() => w.advanceTransport(dut.id,'DELIVERED'), /ordre/);
w.advanceTransport(dut.id,'LOADED','Chargement vérifié');
assert.equal(w.dossier(dut.id).stage,'LOADED');
assert.equal(findDutById(dut.id).status,'VALIDE');
w.addIncident(dut.id,{type:'Panne',severity:'URGENT',description:'Test panne',assignee:'Atelier'});
assert.equal(w.getActions().filter(a=>a.category==='INCIDENT').length,1);
const incident = w.dossier(dut.id).incidents[0];
assert.throws(()=>w.resolveIncident(dut.id,incident.id,''),/résolution/);
w.resolveIncident(dut.id,incident.id,'Réparation terminée');
assert.equal(w.getActions().filter(a=>a.category==='INCIDENT').length,0);
assert.equal(w.dossier(dut.id).incidents[0].resolvedBy,user.name);
w.setCheck(dut.id,'license',true);
assert.equal(readObject(w.LOCAL_KEY)[dut.id].checks.license,true);
const copy = w.duplicateDut(dut.id);
assert.notEqual(copy.id,dut.id); assert.equal(copy.status,'EN_EDITION'); assert.equal(copy.dutNumber,null); assert.equal(copy.qrToken,null); assert.equal(copy.validatedAt,null); assert.equal(w.dossier(copy.id).events.length,0); assert.equal(copy.trajet.dateDepart,'');
assert.throws(()=>w.advanceTransport(copy.id,'LOADED'),/valide/);
await w.attachFile(dut.id,{name:'preuve.pdf',type:'application/pdf',size:20},'Preuve de livraison');
assert.equal(w.dossier(dut.id).files[0].data,'data:application/pdf;base64,dGVzdA==');
await assert.rejects(w.attachFile(dut.id,{type:'text/html',size:1}),/PDF/);
await assert.rejects(w.attachFile(dut.id,{type:'image/png',size:301*1024}),/300 Ko/);
const before=data.get(w.LOCAL_KEY); fail=true;
assert.throws(()=>w.advanceTransport(dut.id,'DEPARTED'),/stockage/);
assert.equal(data.get(w.LOCAL_KEY),before); fail=false;
setPersona({...user,partnerId:'p2'});
assert.throws(()=>w.dossier(dut.id),/périmètre/);
assert.throws(()=>w.duplicateDut(dut.id),/périmètre/);
setPersona({id:'driver',name:'Conducteur',role:'TRANSPORTEUR',transporterId:'t1'});
w.advanceTransport(dut.id,'DEPARTED');
assert.throws(()=>w.duplicateDut(dut.id),/partenaire/);
setPersona(user);
assert.throws(()=>ops.requestNewRange(user,{quantite:1.5,tarifUnitaire:2500}),/entier/);
const request=ops.requestNewRange(user,{quantite:10,tarifUnitaire:2500});
assert.throws(()=>ops.decideRange(request.id,true),/OIC/);
setPersona({id:'oic',name:'Admin OIC',role:'OIC_ADMIN'});
const first=ops.decideRange(request.id,true);
assert.equal(first.rangeStart,101); assert.equal(first.rangeEnd,110);
assert.throws(()=>ops.decideRange(request.id,true),/déjà/);
setPersona(user);
const second=ops.requestNewRange(user,{quantite:20,tarifUnitaire:2500});
setPersona({id:'oic',name:'Admin OIC',role:'OIC_ADMIN'});
assert.equal(ops.decideRange(second.id,true).rangeStart,111);
console.log('Workspace : persistance, transitions, incidents, duplication, fichiers, quotas, périmètres et plages sans chevauchement validés.');

function setPersona(user){writeObject('dut_users',[user]);writeObject('dut_current_user',user);}
